image: php:7.2-fpm

pipelines:
  branches:
    master:
      - step:
          name: production
          caches: 
            - composer
          script:
            - apt-get update && apt-get install -y unzip
            - apt-get install -y openssh-client
            - ssh ubuntu@35.184.177.52 'bash -s' < execute.sh